

services:
  # PostgreSQL database
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: supabase_auth_admin
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supabase_auth_admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # GoTrue with Aliyun SMS support
  gotrue:
    image: gotrue-aliyun:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9998:9999"
    env_file:
      - ./test.aliyun.env
    command: ["gotrue"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
