-- Rename password_set_by_user column to password_is_set on auth.users table
-- 并同步重命名相关索引，统一字段命名为 password_is_set（与 Go 代码和 API JSON 对齐）
-- 注意：如果 password_is_set 列已经存在，则删除旧的 password_set_by_user 列

-- 1. 检查并处理列重命名
-- 如果 password_is_set 已存在，则删除 password_set_by_user 列
-- 如果 password_is_set 不存在，则重命名 password_set_by_user 为 password_is_set
DO $$
DECLARE
  namespace_var TEXT := '{{ index .Options "Namespace" }}';
BEGIN
  -- 检查 password_is_set 列是否存在
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = namespace_var
    AND table_name = 'users' 
    AND column_name = 'password_is_set'
  ) THEN
    -- password_is_set 已存在，删除旧的 password_set_by_user 列（如果存在）
    IF EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = namespace_var
      AND table_name = 'users' 
      AND column_name = 'password_set_by_user'
    ) THEN
      EXECUTE format('ALTER TABLE %I.users DROP COLUMN password_set_by_user', namespace_var);
    END IF;
  ELSE
    -- password_is_set 不存在，重命名 password_set_by_user 为 password_is_set
    IF EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = namespace_var
      AND table_name = 'users' 
      AND column_name = 'password_set_by_user'
    ) THEN
      EXECUTE format('ALTER TABLE %I.users RENAME COLUMN password_set_by_user TO password_is_set', namespace_var);
    END IF;
  END IF;
END $$;

-- 2. 重命名索引：users_password_set_by_user_idx -> users_password_is_set_idx（如果存在）
DO $$
DECLARE
  namespace_var TEXT := '{{ index .Options "Namespace" }}';
  index_exists BOOLEAN;
BEGIN
  -- 检查旧索引是否存在
  SELECT EXISTS (
    SELECT 1 FROM pg_indexes 
    WHERE schemaname = namespace_var
    AND indexname = 'users_password_set_by_user_idx'
  ) INTO index_exists;
  
  IF index_exists THEN
    -- 检查新索引是否已存在
    IF NOT EXISTS (
      SELECT 1 FROM pg_indexes 
      WHERE schemaname = namespace_var
      AND indexname = 'users_password_is_set_idx'
    ) THEN
      EXECUTE format('ALTER INDEX %I.users_password_set_by_user_idx RENAME TO users_password_is_set_idx', namespace_var);
    ELSE
      -- 新索引已存在，删除旧索引
      EXECUTE format('DROP INDEX IF EXISTS %I.users_password_set_by_user_idx', namespace_var);
    END IF;
  END IF;
END $$;

-- 3. 更新列注释中的字段名说明（如果列存在）
DO $$
DECLARE
  namespace_var TEXT := '{{ index .Options "Namespace" }}';
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = namespace_var
    AND table_name = 'users' 
    AND column_name = 'password_is_set'
  ) THEN
    EXECUTE format('COMMENT ON COLUMN %I.users.password_is_set IS %L', 
      namespace_var,
      'Indicates whether the password was explicitly set by the user (true) or automatically generated by the system during OTP/magic link signup (false). Column renamed from password_set_by_user to password_is_set.');
  END IF;
END $$;


