-- Add password_set_by_user column to auth.users table
-- This column tracks whether the password was explicitly set by the user
-- or automatically generated by the system during OTP/magic link signup

-- Add the column with default value FALSE
ALTER TABLE {{ index .Options "Namespace" }}.users 
ADD COLUMN IF NOT EXISTS password_set_by_user BOOLEAN DEFAULT FALSE;

-- Create an index for better query performance
CREATE INDEX IF NOT EXISTS users_password_set_by_user_idx 
ON {{ index .Options "Namespace" }}.users (password_set_by_user);

-- Add a comment to explain the column's purpose
COMMENT ON COLUMN {{ index .Options "Namespace" }}.users.password_set_by_user IS 
'Indicates whether the password was explicitly set by the user (true) or automatically generated by the system during OTP/magic link signup (false)';

-- Update existing users:
-- Users with encrypted_password who have successfully logged in with password should be marked as TRUE
-- This is a best-effort migration based on audit logs

-- Mark users who have password login records in audit log as password_set_by_user = TRUE
UPDATE {{ index .Options "Namespace" }}.users u
SET password_set_by_user = TRUE
WHERE u.encrypted_password IS NOT NULL 
  AND u.encrypted_password != ''
  AND EXISTS (
    SELECT 1 
    FROM {{ index .Options "Namespace" }}.audit_log_entries ale
    WHERE ale.instance_id = u.instance_id
      AND ale.payload->>'user_id' = u.id::text
      AND ale.payload->>'action' = 'login'
      AND ale.payload->>'provider' = 'email'
  );

-- Note: Users who only used OTP/magic link will remain as FALSE (default)
-- Users who set a password but never used it will remain as FALSE (they can set it again)



