-- Rollback: rename password_is_set column back to password_set_by_user on auth.users table

-- 1. 将列名 password_is_set 改回 password_set_by_user
ALTER TABLE {{ index .Options "Namespace" }}.users
RENAME COLUMN password_is_set TO password_set_by_user;

-- 2. 将索引名 users_password_is_set_idx 改回 users_password_set_by_user_idx
ALTER INDEX IF EXISTS {{ index .Options "Namespace" }}.users_password_is_set_idx
RENAME TO users_password_set_by_user_idx;

-- 3. 恢复列注释中的字段名说明
COMMENT ON COLUMN {{ index .Options "Namespace" }}.users.password_set_by_user IS
'Indicates whether the password was explicitly set by the user (true) or automatically generated by the system during OTP/magic link signup (false). Column renamed back from password_is_set to password_set_by_user.';


