-- Rename password_set_by_user column to password_is_set on auth.users table
-- 并同步重命名相关索引，统一字段命名为 password_is_set（与 Go 代码和 API JSON 对齐）

-- 1. 重命名列：password_set_by_user -> password_is_set
ALTER TABLE {{ index .Options "Namespace" }}.users
RENAME COLUMN password_set_by_user TO password_is_set;

-- 2. 重命名索引：users_password_set_by_user_idx -> users_password_is_set_idx
ALTER INDEX IF EXISTS {{ index .Options "Namespace" }}.users_password_set_by_user_idx
RENAME TO users_password_is_set_idx;

-- 3. 更新列注释中的字段名说明（如果原来存在）
COMMENT ON COLUMN {{ index .Options "Namespace" }}.users.password_is_set IS
'Indicates whether the password was explicitly set by the user (true) or automatically generated by the system during OTP/magic link signup (false). Column renamed from password_set_by_user to password_is_set.';


